# Generated by Django 4.2.5 on 2023-09-15 07:43

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplyoee_name', models.CharField(max_length=100)),
                ('mobile_number', models.PositiveIntegerField()),
                ('date_of_birth', models.DateTimeField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('is_AWS', models.BooleanField(default=False)),
                ('is_Full_Stack_Developer', models.BooleanField(default=False)),
                ('is_DevOps', models.BooleanField(default=False)),
            ],
        ),
    ]
